### ISSUE TITLE
Rapport d'activité

### ISSUE THREAD

**Issue by louib** [nilovna/EnceFAL#13]
Journalier et fin de la foire aux livres. Envoyé à gérantE

**Comment by louib** [comment]
Devrait être fait avec une custom command : 
https://docs.djangoproject.com/en/dev/howto/custom-management-commands/

on va ensuite lancer la commande avec un cron job.

**Comment by GitMyCode** [comment]
Proposition de faire une page "rapport" dans laquel un employer peux choisir la journée et voir le rapport de cette journée a la place d'un envoie de e-mail
