### ISSUE TITLE
Page de vente

### ISSUE THREAD

**Issue by nilovna** [nilovna/EnceFAL#16]

**Comment by louib** [comment]
il reste quelques trucs à faire:
- faire une actions pour annuler les factures (et un bouton "Annuler une vente", qui mene au listing)
- quand le champ identifiant est clearé, on clear aussi les autres champs (pour enlever un exemplaire)
- vérifier que l'exemplaire est bien en vente avant de l'ajouter à la facture

**Comment by louib** [comment]
Pas mal ok, il resterait juste a afficher des erreurs dans le cas ou l'exemplaire n'existe pas ou n'est pas en vente, mais selon la logique, ca devrait pas arriver.
