### ISSUE TITLE
Rendre interface admin homogène.

### ISSUE THREAD

**Issue by louib** [nilovna/EnceFAL#18]
Le style est pas le meme partout dans l'interface admin.
- Le bouton lors de l'identification.
- Les stripes bleues dans le menu admin.

**Comment by louib** [comment]
Ca semble terminé. Il te reste des trucs à faire?

**Comment by nilovna** [comment]
Ouep, pas terminé, encore des templates à corriger!
- *
  ____________________________________________
  _Nilovna Bascunan-Vasquez_
  Étudiante au bac en informatique et génie logiciel
  Université du Québec À Montréal (UQAM)
  514-991-1931
  http://www.nilovna.com
