### ISSUE TITLE
S'assurer que buildout est bien "setté"

### ISSUE THREAD

**Issue by nilovna** [nilovna/EnceFAL#2]
J'ai fais ça un peu à l'aveuglette, je ne suis pas sure que je l'ai bien mis en place.

**Comment by louib** [comment]
Il manquait certains eggs, je lai ai ajoutés. Jai aussi ajouté les trucs manquants dans installed apps.

Jai ajouté south, pcq ca buche et je commence a mamuser pas mal avec ca. On va p-e pas sen servir mais qui sait...
