### ISSUE TITLE
[Modification] Besoin-ADÉESE

### ISSUE THREAD

**Issue by ventilooo** [nilovna/EnceFAL#32]
**J'ai rencontrer les gens de l'Association facultaire des science de l'éducation.**
Voici un listing de leurs besoin pour utiliser encefal :  
Ajout:
- module de chèque (vérifier la taille)
- scanner ISBN
- impression automatique étiquette 
- auto-gen rapport
  - des vente pour une date donné
  - période donné
  - rapport vente 
    - information (mail, livre, date(heure), montant).
- module Taxe (remise de monnaie) (arrondissement basique =+ )
- module compte vendeur  
  - gestion module asso(cote)
  - date d'entré du livre.
  - adresse du vendeur.
- Gestion droit d'accès BD 
- Portail commun
- Prix NEUF: Prix Membre coop uqam (accès BD)
- (bonus) prix suggére (moyenne des prix des livres en BD)
- Affiche de prix [prix de vente, prix neuf, prix avec cote, prix final].
- accès modification tps-tvq et cote.
- module liste d'attente.
## Posibilité d'indéminsation Des Étudiant qui travaille sur  encefal 
- DeadLine (aout)
- Iteration (1 mois)
- Possibilité d'accès SLU ADESSE.

@nilovna @marconius  @GitMyCode  @louib

**Comment by marconius** [comment]
salut! Je ne peux pas travailler sur ce projet car je n'ai aucun temps libre à y consacrer, mais je peux vous offrir un petit suggestion.

Il y a beaucoup de demandes de «features», mais peut-être il n'y a pas grand monde pour entreprendre l'ouvrage. Ce que je sugère c'est de diviser le travail en «user stories» indépendents, puis les prioriser avec le client pour pouvoir travailler en mode «Kanban». Avec un Kanban, quand qqun peut prendre un story il ou elle va pouvoir prendre celle qui est plus priotaire.

Mon 2 cents

**Comment by ventilooo** [comment]
C'est ici que ça se passe ! https://github.com/AESSUQAM/EnceFAL
