### ISSUE TITLE
Créer HTML pour interface publique et "plugger" avec Foundation

### ISSUE THREAD

**Issue by nilovna** [nilovna/EnceFAL#4]

**Comment by nilovna** [comment]
![20130604_203551](https://f.cloud.github.com/assets/906237/659972/ee6e7f5a-d6d1-11e2-9b15-1caa192bb87e.jpg)

**Comment by louib** [comment]
Foundation n'est pas retenu pour l'interface publique.
L'interface publique est deja terminée.
